name: mlflow CI

on:
  push:
    branches: [main]
    paths:
      - "MLProject/**"
      - ".github/workflows/mlflow-ci.yml"
  workflow_dispatch: {}

env:
  MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
  MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
  MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Setup PIP
        run: python3 -m pip install --upgrade pip

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run MLFlow Project
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        working-directory: MLProject
        run: mlflow run . --env-manager=local

      - name: Read Best Model Run ID
        run: |
          RUN_ID=$(cat MLProject/artifacts/best_run_id.txt)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Best Run ID: $RUN_ID"

      - name: Install Docker Python SDK
        run: pip install docker

      - name: Upload ML Artifacts to GitHub
        if: env.RUN_ID != ''
        uses: actions/upload-artifact@v4
        with:
          name: breast-cancer-model-${{ env.RUN_ID }}
          path: MLProject/artifacts/
          retention-days: 90

      - name: Build Docker Model
        if: env.RUN_ID != ''
        run: |
          echo "Building Docker Image using RUN_ID=$RUN_ID"
          mlflow models build-docker --model-uri "runs:/$RUN_ID/model" --name "breast-cancer-prediction"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag Docker Image
        run: |
          docker tag breast-cancer-prediction:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-prediction:${{ env.RUN_ID }}

          docker tag breast-cancer-prediction:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-prediction:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-prediction:${{ env.RUN_ID }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/breast-cancer-prediction:latest
